# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitswitch < Formula
  desc "Stop committing as the wrong person — directory-bound git identities"
  homepage "https://github.com/target-ops/gitswitch"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/target-ops/gitswitch/releases/download/v1.1.1/gitswitch-1.1.1-darwin-amd64.tar.gz"
      sha256 "0cfe7f3ce30de20f7bce193cd2c6374bb7da41d3e1e07feb1f85a24667eb1af8"

      define_method(:install) do
        bin.install "gitswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/target-ops/gitswitch/releases/download/v1.1.1/gitswitch-1.1.1-darwin-arm64.tar.gz"
      sha256 "cfeb22168f216d17750e25e76b63c09f13346ab3e6c72aa79b44e85a2eaca837"

      define_method(:install) do
        bin.install "gitswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/target-ops/gitswitch/releases/download/v1.1.1/gitswitch-1.1.1-linux-amd64.tar.gz"
      sha256 "f491780cfa5e48ad915feeb6746217118fc0e23d37ec1621c92a1ea72f0013f4"
      define_method(:install) do
        bin.install "gitswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/target-ops/gitswitch/releases/download/v1.1.1/gitswitch-1.1.1-linux-arm64.tar.gz"
      sha256 "f0ab5bb9fc9e469c6edadb27f5d4dac915c9691d288b978c1bfd9cda40e94240"
      define_method(:install) do
        bin.install "gitswitch"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitswitch --version")
    help = shell_output("#{bin}/gitswitch --help")
    %w[init use guard doctor why].each do |cmd|
      assert_match cmd, help
    end
  end
end
